/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

// // 不適用於 PHP 的 FFI::cdef()
// #ifndef __RUST_CORE__
// #define __RUST_CORE__
// #ifdef __cplusplus
// extern "C" {
// #endif

/** <No documentation available> */
void
free_string (
    char * char_boxed);

/** <No documentation available> */
char *
process_request (
    char const * peer_ip_p,
    char const * peer_port_p,
    char const * url_p,
    char const * method_p,
    char const * headers_data_p,
    char const * body_data_p,
    char const * files_data_p);


// // 不適用於 PHP 的 FFI::cdef()
// #ifdef __cplusplus
// } /* extern \"C\" */
// #endif
//
// #endif /* __RUST_CORE__ */
